version: '3.4'

services:
  jupyter_notebook:
    build: .
    image: trevor.notebook:1.0.0
    container_name: py3_notebook

    environment:
      - GRANT_SUDO=true
      - GEOS_DIR=/usr/local/geos
    
    user: root
    privileged: true
    
    network_mode: "bridge"
    ports:
      - "10888:8888"

    volumes:
      - $PWD/workspace:/home/jovyan
      - $PWD/downloads:/home/jovyan/downloads
      - $PWD/pkg/:/home/jovyan/pkg

    deploy:
      restart_policy:
        condition: on-failure